Repository NitBravoA92/recipe-app, pull requests merged in 2023-10, with the labels that each got.

#20 Create login and registration page
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/models/ability.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/recipe_food.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20231009184248_devise_create_users.rb
  db/migrate/20231009195435_create_foods.rb
  db/migrate/20231009204526_create_recipes.rb
  db/migrate/20231009204948_create_recipe_foods.rb
  db/schema.rb
  package-lock.json
  package.json
  spec/models/food_spec.rb
  spec/models/recipe_food_spec.rb
  spec/models/recipe_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#21 Add food list page
  app/assets/stylesheets/application.css
  app/controllers/foods_controller.rb
  app/helpers/foods_helper.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/recipe_food.rb
  app/models/user.rb
  app/views/foods/index.html.erb
  app/views/partials/_table_food_item.html.erb
  config/routes.rb
  spec/helpers/foods_helper_spec.rb
  spec/requests/foods_spec.rb
  spec/views/foods/index.html.erb_spec.rb
Labels: enhancement

#23 Add new food form
  app/assets/stylesheets/application.css
  app/controllers/foods_controller.rb
  app/models/food.rb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
Labels: enhancement

#24 Add delete food functionality
  app/assets/stylesheets/application.css
  app/controllers/foods_controller.rb
  app/models/food.rb
  app/views/partials/_table_food_item.html.erb
Labels: enhancement

#25 Public recipes page
  app/controllers/recipe_foods_controller.rb
  app/helpers/recipe_foods_helper.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/recipe_food.rb
  app/views/recipe_foods/index.html.erb
  config/routes.rb
  db/migrate/20231010193737_change_data_type_for_quantity.rb
  db/schema.rb
  spec/helpers/recipe_foods_helper_spec.rb
  spec/requests/recipe_foods_spec.rb
Labels: enhancement

#28 Delete recipe
  app/controllers/recipes_controller.rb
Labels: enhancement

#29 Tests recipes
  spec/factories/recipes.rb
  spec/features/foods/food_index_spec.rb
  spec/features/foods/food_new_spec.rb
  spec/features/recipes/recipe_index_spec.rb
  spec/features/recipes/recipe_new_spec.rb
  spec/models/recipe_spec.rb
  spec/requests/recipes_spec.rb
Labels: enhancement, testing

#30 Create recipe details page
  app/assets/stylesheets/application.css
  app/controllers/recipe_foods_controller.rb
  app/controllers/recipes_controller.rb
  app/helpers/foods_helper.rb
  app/helpers/recipe_helper.rb
  app/models/ability.rb
  app/models/recipe_food.rb
  app/views/partials/_table_recipe_foods_item.html.erb
  app/views/recipes/show.html.erb
  config/routes.rb
Labels: enhancement

#31 Form recipe foods
  app/controllers/recipe_foods_controller.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/recipe_food.rb
  app/views/partials/_table_recipe_foods_item.html.erb
  app/views/recipe_foods/edit.html.erb
  app/views/recipe_foods/new.html.erb
  app/views/recipes/show.html.erb
  config/routes.rb
Labels: enhancement

#32 General shopping list page
  .gitignore
  app/controllers/recipe_foods_controller.rb
  app/models/food.rb
  app/views/partials/_table_general_shopping_list.html.erb
  app/views/recipe_foods/general_shopping_list.html.erb
  config/routes.rb
Labels: enhancement

#33 Create navigation menu and improve the css of the App
  app/assets/images/body-bg.png
  app/assets/images/home-bg.jpg
  app/assets/stylesheets/application.css
  app/javascript/application.js
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/partials/_navbar.html.erb
  app/views/partials/_public_toggle_button.html.erb
  app/views/partials/_table_food_item.html.erb
  app/views/partials/_table_recipe_foods_item.html.erb
  app/views/recipe_foods/edit.html.erb
  app/views/recipe_foods/general_shopping_list.html.erb
  app/views/recipe_foods/index.html.erb
  app/views/recipe_foods/new.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/show.html.erb
  spec/features/recipes/recipe_index_spec.rb
Labels: enhancement

#35 N plus 1 queries
  Gemfile
  Gemfile.lock
  LICENSE
  README.md
  app/assets/stylesheets/application.css
  app/controllers/recipe_foods_controller.rb
  app/controllers/recipes_controller.rb
  app/helpers/recipe_helper.rb
  app/models/food.rb
  app/models/recipe.rb
  app/views/foods/new.html.erb
  app/views/layouts/application.html.erb
  app/views/recipes/show.html.erb
  config/environments/development.rb
  spec/models/recipe_food_spec.rb
  spec/requests/recipes_spec.rb
Labels: documentation, testing
